


{

		[_x, [

			//PISTOLS
			"rhsusf_weap_m1911a1",
			"rhs_weap_M320",
			"rhsusf_weap_glock17g4",
			"rhsusf_weap_m9",

			//LAUNCHER
			"rhs_weap_fgm148",
			"rhs_weap_m72a7",
			"rhs_weap_fim92",
			"tf47_m3maaws",
			"tf47_optic_m3maaws",
			"tf47_at4_heat",
			"tf47_at4_HEDP",
			"tf47_at4_HP",
			"tf47_smaw",
			"tf47_smaw_green",
			"tf47_optic_smaw",

			//PRIMARY
			"rhs_weap_hk416d145",
			"rhs_weap_hk416d145_m320",
			"rhs_weap_hk416d10",
			"rhs_weap_hk416d10_m320",
			"rhs_weap_hk416d10_LMT",
			"rhs_weap_M107",
			"rhs_weap_M107_w",
			"rhs_weap_m14ebrri",
			"rhs_weap_m16a4",
			"rhs_weap_m16a4_carryhandle",
			"rhs_weap_m16a4_carryhandle_pmag",
			"rhs_weap_m16a4_carryhandle_M203",
			"rhs_weap_m16a4_pmag",
			"rhs_weap_XM2010",
			"rhs_weap_XM2010_wd",
			"rhs_weap_m24sws",
			"rhs_weap_m24sws_blk",
			"rhs_weap_m24sws_ghillie",
			"rhs_weap_m240B",
			"rhs_weap_m240B_CAP",
			"rhs_weap_m240G",
			"rhs_weap_m249_pip_L",
			"rhs_weap_m249_pip_L_para",
			"rhs_weap_m249_pip_L_vfg",
			"rhs_weap_m249_pip_S",
			"rhs_weap_m249_pip_S_para",
			"rhs_weap_m249_pip_S_vfg",
			"rhs_weap_m27iar",
			"rhs_weap_m27iar_grip",
			"rhs_weap_m32",
			"rhs_weap_m4",
			"rhs_weap_m4_carryhandle_mstock",
			"rhs_weap_m4_carryhandle",
			"rhs_weap_m4_carryhandle_pmag",
			"rhs_weap_m4_m203",
			"rhs_weap_m4_m203S",
			"rhs_weap_m4_m320",
			"rhs_weap_m4_pmag",
			"rhs_weap_m4_mstock",
			"rhs_weap_m4a1_carryhandle",
			"rhs_weap_m4a1_carryhandle_m203",
			"rhs_weap_m4a1_carryhandle_m203S",
			"rhs_weap_m4a1_carryhandle_pmag",
			"rhs_weap_m4a1_carryhandle_mstock",
			"rhs_weap_m4a1_blockII",
			"rhs_weap_m4a1_blockII_wd",
			"rhs_weap_m4a1_blockII_M203",
			"rhs_weap_m4a1_blockII_bk",
			"rhs_weap_m4a1_blockII_M203_bk",
			"rhs_weap_m4a1_blockII_M203_wd",
			"rhs_weap_m4a1_blockII_KAC_bk",
			"rhs_weap_m4a1_blockII_KAC",
			"rhs_weap_m4a1_blockII_KAC_wd",
			"rhs_weap_m4a1",
			"rhs_weap_m4a1_m203",
			"rhs_weap_m4a1_m203s",
			"rhs_weap_m4a1_m320",
			"rhs_weap_m4a1_pmag",
			"rhs_weap_m4a1_mstock",
			"rhs_weap_M590_8RD",
			"rhs_weap_M590_5RD",
			"rhs_weap_sr25",
			"rhs_weap_sr25_wd",
			"rhs_weap_sr25_ec",
			"rhs_weap_sr25_ec_wd",
			"rhs_weap_mk18",
			"rhs_weap_mk18_wd",
			"rhs_weap_mk18_m320",
			"rhs_weap_mk18_bk",
			"rhs_weap_mk18_KAC_bk",
			"rhs_weap_mk18_KAC",
			"rhs_weap_mk18_KAC_wd",
			"rhsusf_weap_MP7A1_base_f",
			"ACE_Vector"

		],false, true] call xla_fnc_addVirtualWeaponCargo;

		[_X, [

			// Mortar
			"ACE_1Rnd_82mm_Mo_HE",
			"ACE_1Rnd_82mm_Mo_Smoke",
			"ACE_1Rnd_82mm_Mo_Illum",
			"ACE_1Rnd_82mm_Mo_HE_Guided",
			"ACE_1Rnd_82mm_Mo_HE_LaserGuided",


			//LAUNCHER AMMO
			"rhs_fim92_mag",
			"tf47_m3maaws_HEAT",
			"tf47_m3maaws_HEDP",
			"tf47_m3maaws_HE",
			"tf47_m3maaws_SMOKE",
			"tf47_m3maaws_ILLUM",
			"tf47_at4_m_HEAT",
			"tf47_at4_m_HEDP",
			"tf47_at4_m_HP",
			"tf47_smaw_HEAA",
			"tf47_smaw_HEDP",
			"tf47_smaw_SR",
			"rhs_weap_fgm148",
			"rhs_weap_M136",
			"rhs_weap_M136_hedp",
			"rhs_weap_M136_hp",
			"rhs_weap_m72a7",
			"rhs_weap_fim92",
			"rhs_weap_smaw",
			"rhs_weap_smaw_green",

			//PISTOL AMMO
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_17Rnd_9x19_JHP",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_15Rnd_9x19_JHP",
			"rhsusf_mag_15Rnd_9x19_FMJ",

			//RIFLE AMMO
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk262_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_No_Tracer",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Green",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Yellow",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Orange",
			"rhs_mag_30Rnd_556x45_M200_Stanag",
			"rhsusf_mag_10Rnd_STD_50BMG_M33",
			"rhsusf_mag_10Rnd_STD_50BMG_mk211",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m993_Mag",
			"rhsusf_20Rnd_762x51_m62_Mag",
			"rhsusf_5Rnd_300winmag_xm2010",
			"rhsusf_100Rnd_762x51",
			"rhsusf_100Rnd_762x51_m61_ap",
			"rhsusf_100Rnd_762x51_m62_tracer",
			"rhsusf_100Rnd_762x51_m80a1epr",
			"rhsusf_100Rnd_762x51_m82_blank",
			"rhsusf_50Rnd_762x51_m993",
			"rhsusf_100Rnd_762x51_m993",
			"rhs_200rnd_556x45_M_SAW",
			"rhs_200rnd_556x45_B_SAW",
			"rhs_200rnd_556x45_T_SAW",
			"rhsusf_100Rnd_556x45_soft_pouch",
			"rhsusf_200Rnd_556x45_soft_pouch",
			"rhsusf_100Rnd_556x45_M200_soft_pouch",
			"rhsusf_5Rnd_00Buck",
			"rhsusf_5Rnd_doomsday_Buck",
			"rhsusf_5Rnd_Slug",
			"rhsusf_5Rnd_HE",
			"rhsusf_5Rnd_FRAG",
			"rhsusf_mag_40Rnd_46x30_FMJ",
			"rhsusf_mag_40Rnd_46x30_JHP",
			"rhsusf_mag_40Rnd_46x30_AP",

			//ULG Ammo
			"rhs_mag_M441_HE",
			"rhs_mag_M433_HEDP",
			"rhs_mag_m4009",
			"rhs_mag_m576",
			"rhs_mag_M585_white",
			"rhs_mag_m661_green",
			"rhs_mag_m662_red",
			"rhs_mag_m713_Red",
			"rhs_mag_m714_White",
			"rhs_mag_m715_Green",
			"rhs_mag_m716_yellow",
			"rhsusf_mag_6Rnd_M441_HE",
			"rhsusf_mag_6Rnd_M433_HEDP",
			"rhsusf_mag_6Rnd_M576_Buckshot",
			"rhsusf_mag_6Rnd_M781_Practice",
			"rhsusf_mag_6Rnd_m4009",
			"rhsusf_mag_6Rnd_M585_white",
			"rhsusf_mag_6Rnd_m661_green",
			"rhsusf_mag_6Rnd_m662_red",
			"rhsusf_mag_6Rnd_M713_red",
			"rhsusf_mag_6Rnd_M714_white",
			"rhsusf_mag_6Rnd_M715_green",
			"rhsusf_mag_6Rnd_M716_yellow",
			"ACE_HuntIR_M203",

			//Explosives
			"SatchelCharge_Remote_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"DemoCharge_Remote_Mag",
			"rhs_mine_M19_mag",
			"rhsusf_m112_mag",

			//GRENADES
			"rhs_mag_an_m14_th3",
			"rhs_mag_an_m8hc",
			"rhs_mag_fakel",
			"rhs_mag_fakels",
			"rhs_mag_m18_yellow",
			"rhs_mag_m18_green",
			"rhs_mag_m18_purple",
			"rhs_mag_m18_red",
			"rhs_mag_m67",
			"rhs_mag_m69",
			"rhs_mag_m7a3_cs",
			"rhs_mag_mk84",
			"rhs_mag_mk3a2",

			"ACE_HandFlare_White",
			"ACE_HandFlare_Red",
			"ACE_HandFlare_Green",
			"ACE_HandFlare_Yellow",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_yellow",
			"Chemlight_blue",
			"B_IR_Grenade",
			"rhs_fgm148_magazine_AT",
			"rhsusf_5Rnd_762x51_m118_special_Mag",
			"rhsusf_5Rnd_762x51_m993_Mag",
			"rhsusf_5Rnd_762x51_m62_Mag",
			//LASER BATTERIES
			"Laserbatteries"

		], false, true] call xla_fnc_addVirtualMagazineCargo;

		[_X, [

			//BACKPACKS
			"B_rhsusf_B_BACKPACK",
			"rhsusf_assault_eagleaiii_coy",

			"rhsusf_assault_eagleaiii_ocp",
			"rhsusf_assault_eagleaiii_ucp",
			"rhsusf_falconii_coy",
			"rhsusf_falconii_mc",
			"rhsusf_falconii",

			"tf_rt1523g_big_rhs",
			"tf_rt1523g_rhs",
			"tf_rt1523g_sage",

			"RHS_M2_Gun_Bag",
			"RHS_M2_Tripod_Bag",
			"rhs_M252_Gun_Bag",
			"rhs_M252_Bipod_Bag",
			"RHS_M2_MiniTripod_Bag",
			"RHS_Mk19_Gun_Bag",
			"RHS_Mk19_Tripod_Bag",
			"rhs_Tow_Gun_Bag",
			"rhs_TOW_Tripod_Bag",

			"B_Kitbag_cbr",
			"B_Kitbag_rgr",
			"B_Kitbag_mcamo",
			"B_Parachute",
			"ACE_TacticalLadder_Pack",
			"ACE_NonSteerableParachute",

			"B_Mortar_01_support_F",
			"B_Mortar_01_weapon_F",
			"milgp_bp_Breacher_cb",
			"milgp_bp_Breacher_mc",
			"milgp_bp_Breacher_rgr",

			"milgp_bp_hydration_cb",
			"milgp_bp_hydration_mc",
			"milgp_bp_hydration_rgr",

			"milgp_bp_Pointman_cb",
			"milgp_bp_Pointman_mc",
			"milgp_bp_Pointman_rgr",

			"milgp_bp_Tomahawk_cb",
			"milgp_bp_Tomahawk_mc",
			"milgp_bp_Tomahawk_rgr",

			"fatpack_coy",
			"fatpack_od",

			"tfw_ilbe_a_coy",
			"tfw_ilbe_coy",
			"tfw_ilbe_blade_coy",
			"tfw_ilbe_dd_coy",

			"tfw_ilbe_a_gr",
			"tfw_ilbe_gr",
			"tfw_ilbe_blade_gr",
			"tfw_ilbe_dd_gr",

			"tfw_ilbe_a_d",
			"tfw_ilbe_d",
			"tfw_ilbe_blade_d",
			"tfw_ilbe_dd_d",

			"tfw_ilbe_a_wd",
			"tfw_ilbe_wd",
			"tfw_ilbe_blade_wd",
			"tfw_ilbe_dd_wd"
		], false, true] call xla_fnc_addVirtualBackpackCargo;


		[_X, [
			//UNIFORM
			"rhs_uniform_cu_ocp",
			"rhs_uniform_cu_ucp",
			"rhs_uniform_FROG01_d",
			"rhs_uniform_FROG01_wd",
			"rhs_uniform_g3_m81",
			"rhs_uniform_g3_mc",
			"rhs_uniform_g3_rgr",
			"rhs_uniform_g3_tan",
			"rhs_uniform_g3_blk",
			"U_B_Wetsuit",
			"U_B_FullGhillie_lsh",
			"U_B_FullGhillie_sard",
			"U_B_FullGhillie_ard",
			"U_B_PilotCoveralls",
			"U_B_HeliPilotCoveralls",
			"milgp_u_fleece_grey_g3_field_pants_M81",
			"milgp_u_fleece_grey_g3_field_pants_mc",
			"milgp_u_fleece_khk_g3_field_pants_mc",
			"milgp_u_fleece_rgr_g3_field_pants_rgr",
			"milgp_u_fleece_rgr_g3_field_pants_M81",
			"milgp_u_fleece_rgr_g3_field_pants_mc",
			//VESTS
			"rhsusf_iotv_ocp_Grenadier",
			"rhsusf_iotv_ocp_Medic",
			"rhsusf_iotv_ocp",
			"rhsusf_iotv_ocp_Repair",
			"rhsusf_iotv_ocp_Rifleman",
			"rhsusf_iotv_ocp_SAW",
			"rhsusf_iotv_ocp_Squadleader",
			"rhsusf_iotv_ocp_Teamleader",
			"rhsusf_spcs_ocp_rifleman",
			"rhsusf_spcs_ocp",
			"rhsusf_iotv_ucp_Grenadier",
			"rhsusf_iotv_ucp_Medic",
			"rhsusf_iotv_ucp",
			"rhsusf_iotv_ucp_Repair",
			"rhsusf_iotv_ucp_Rifleman",
			"rhsusf_iotv_ucp_SAW",
			"rhsusf_iotv_ucp_Teamleader",
			"rhsusf_iotv_ucp_Squadleader",
			"rhsusf_spcs_Ucp_rifleman",
			"rhsusf_spcs_ucp",
			"rhsusf_spc",
			"rhsusf_spc_teamleader",
			"rhsusf_spc_squadleader",
			"rhsusf_spc_rifleman",
			"rhsusf_spc_patchless_radio",
			"rhsusf_spc_patchless",
			"rhsusf_spc_marksman",
			"rhsusf_spc_mg",
			"rhsusf_spc_light",
			"rhsusf_spc_iar",
			"rhsusf_spc_crewman",
			"rhsusf_spc_corpsman",
			"V_Rangemaster_belt",
			"V_RebreatherB",
			"V_TacVestIR_blk",

			"milgp_v_jpc_assaulter_cb",
			"milgp_v_jpc_assaulter_belt_cb",
			"milgp_v_jpc_Grenadier_cb",
			"milgp_v_jpc_Grenadier_belt_cb",
			"milgp_v_jpc_hgunner_cb",
			"milgp_v_jpc_hgunner_belt_cb",
			"milgp_v_jpc_Light_cb",
			"milgp_v_jpc_Marksman_cb",
			"milgp_v_jpc_marksman_belt_cb",
			"milgp_v_jpc_Medic_cb",
			"milgp_v_jpc_medic_belt_cb",
			"milgp_v_jpc_TeamLeader_cb",
			"milgp_v_jpc_teamleader_belt_cb",

			"milgp_v_marciras_assaulter_cb",
			"milgp_v_marciras_assaulter_belt_cb",
			"milgp_v_marciras_grenadier_cb",
			"milgp_v_marciras_grenadier_belt_cb",
			"milgp_v_marciras_hgunner_cb",
			"milgp_v_marciras_hgunner_belt_cb",
			"milgp_v_marciras_light_cb",
			"milgp_v_marciras_marksman_cb",
			"milgp_v_marciras_marksman_belt_cb",
			"milgp_v_marciras_medic_cb",
			"milgp_v_marciras_medic_belt_cb",
			"milgp_v_marciras_teamleader_CB",
			"milgp_v_marciras_teamleader_belt_CB",

			"milgp_v_jpc_assaulter_mc",
			"milgp_v_jpc_assaulter_belt_mc",
			"milgp_v_jpc_Grenadier_mc",
			"milgp_v_jpc_Grenadier_belt_mc",
			"milgp_v_jpc_hgunner_mc",
			"milgp_v_jpc_hgunner_belt_mc",
			"milgp_v_jpc_Light_mc",
			"milgp_v_jpc_Marksman_mc",
			"milgp_v_jpc_marksman_belt_mc",
			"milgp_v_jpc_Medic_mc",
			"milgp_v_jpc_medic_belt_mc",
			"milgp_v_jpc_TeamLeader_mc",
			"milgp_v_jpc_teamleader_belt_mc",

			"milgp_v_marciras_assaulter_mc",
			"milgp_v_marciras_assaulter_belt_mc",
			"milgp_v_marciras_grenadier_mc",
			"milgp_v_marciras_grenadier_belt_mc",
			"milgp_v_marciras_hgunner_mc",
			"milgp_v_marciras_hgunner_belt_mc",
			"milgp_v_marciras_light_mc",
			"milgp_v_marciras_marksman_mc",
			"milgp_v_marciras_marksman_belt_mc",
			"milgp_v_marciras_medic_mc",
			"milgp_v_marciras_medic_belt_mc",
			"milgp_v_marciras_teamleader_mc",
			"milgp_v_marciras_teamleader_belt_mc",

			"milgp_v_jpc_assaulter_rgr",
			"milgp_v_jpc_assaulter_belt_rgr",
			"milgp_v_jpc_Grenadier_rgr",
			"milgp_v_jpc_Grenadier_belt_rgr",
			"milgp_v_jpc_hgunner_rgr",
			"milgp_v_jpc_hgunner_belt_rgr",
			"milgp_v_jpc_Light_rgr",
			"milgp_v_jpc_Marksman_rgr",
			"milgp_v_jpc_marksman_belt_rgr",
			"milgp_v_jpc_Medic_rgr",
			"milgp_v_jpc_medic_belt_rgr",
			"milgp_v_jpc_TeamLeader_rgr",
			"milgp_v_jpc_teamleader_belt_rgr",

			"milgp_v_marciras_assaulter_rgr",
			"milgp_v_marciras_assaulter_belt_rgr",
			"milgp_v_marciras_grenadier_rgr",
			"milgp_v_marciras_grenadier_belt_rgr",
			"milgp_v_marciras_hgunner_rgr",
			"milgp_v_marciras_hgunner_belt_rgr",
			"milgp_v_marciras_light_rgr",
			"milgp_v_marciras_marksman_rgr",
			"milgp_v_marciras_marksman_belt_rgr",
			"milgp_v_marciras_medic_rgr",
			"milgp_v_marciras_medic_belt_rgr",
			"milgp_v_marciras_teamleader_rgr",
			"milgp_v_marciras_teamleader_belt_rgr",

			"cpc_communications_coy",
			"cpc_Fast_coy",
			"cpc_light_coy",
			"cpc_medical_coy",
			"cpc_tl_coy",
			"cpc_weapons_coy",
			"cpc_communicationsbelt_coy",
			"cpc_Fastbelt_coy",
			"cpc_lightbelt_coy",
			"cpc_medicalbelt_coy",
			"cpc_tlbelt_coy",
			"cpc_weaponsbelt_coy",

			"cpc_communications_mc",
			"cpc_Fast_mc",
			"cpc_light_mc",
			"cpc_medical_mc",
			"cpc_tl_mc",
			"cpc_weapons_mc",
			"cpc_communicationsbelt_mc",
			"cpc_Fastbelt_mc",
			"cpc_lightbelt_mc",
			"cpc_medicalbelt_mc",
			"cpc_tlbelt_mc",
			"cpc_weaponsbelt_mc",

			"cpc_communications_rngr",
			"cpc_Fast_rngr",
			"cpc_light_rngr",
			"cpc_medical_rngr",
			"cpc_tl_rngr",
			"cpc_weapons_rngr",
			"cpc_communicationsbelt_rngr",
			"cpc_Fastbelt_rngr",
			"cpc_lightbelt_rngr",
			"cpc_medicalbelt_rngr",
			"cpc_tlbelt_rngr",
			"cpc_weaponsbelt_rngr",

			"lbt_comms_coy",
			"lbt_fast_coy",
			"lbt_light_coy",
			"lbt_medical_coy",
			"lbt_operator_coy",
			"lbt_pouchless_coy",
			"lbt_tl_coy",
			"lbt_weapons_coy",

			"lbt_comms_mc",
			"lbt_fast_mc",
			"lbt_light_mc",
			"lbt_medical_mc",
			"lbt_operator_mc",
			"lbt_pouchless_mc",
			"lbt_tl_mc",
			"lbt_weapons_mc",

			"lbt_comms_od",
			"lbt_fast_rngr",
			"lbt_light_rngr",
			"lbt_medical_rngr",
			"lbt_operator_rngr",
			"lbt_pouchless_rngr",
			"lbt_tl_rngr",
			"lbt_weapons_rngr",

			//HEADGEAR

			"milgp_h_airframe_Combat_CB",
			"milgp_h_airframe_Light_CB",
			"milgp_h_airframe_tactical_CB",
			"milgp_h_airframe_Combat_KHK",
			"milgp_h_airframe_Light_KHK",
			"milgp_h_airframe_tactical_KHK",
			"milgp_h_airframe_Combat_rgr",
			"milgp_h_airframe_Light_rgr",
			"milgp_h_airframe_tactical_rgr",


			"rhsusf_ach_bare",
			"rhsusf_ach_bare_des",
			"rhsusf_ach_bare_des_ess",
			"rhsusf_ach_bare_des_headset",
			"rhsusf_ach_bare_des_headset_ess",
			"rhsusf_ach_bare_ess",
			"rhsusf_ach_bare_headset",
			"rhsusf_ach_bare_headset_ess",
			"rhsusf_ach_bare_semi",
			"rhsusf_ach_bare_semi_ess",
			"rhsusf_ach_bare_semi_headset",
			"rhsusf_ach_bare_semi_headset_ess",
			"rhsusf_ach_bare_tan",
			"rhsusf_ach_bare_tan_ess",
			"rhsusf_ach_bare_tan_headset",
			"rhsusf_ach_bare_tan_headset_ess",
			"rhsusf_ach_bare_wood",
			"rhsusf_ach_bare_wood_ess",
			"rhsusf_ach_bare_wood_headset",
			"rhsusf_ach_bare_wood_headset_ess",
			"rhsusf_ach_helmet_M81",
			"rhsusf_ach_helmet_ocp",
			"rhsusf_ach_helmet_ocp_ess",
			"rhsusf_ach_helmet_ocp_headset",
			"rhsusf_ach_helmet_ocp_headset_ess",
			"rhsusf_ach_helmet_camo_ocp",
			"rhsusf_ach_helmet_ocp_norotos",
			"rhsusf_ach_helmet_ucp",
			"rhsusf_ach_bare_ucp_ess",
			"rhsusf_ach_bare_ucp_headset",
			"rhsusf_ach_bare_ucp_headset_ess",
			"rhsusf_ach_helmet_ucp_norotos",
			"rhsusf_cvc_green_helmet",
			"rhsusf_cvc_green_ess",
			"rhsusf_cvc_helmet",
			"rhsusf_cvc_ess",
			"rhs_Booniehat_m81",
			"rhs_booniehat2_marpatd",
			"rhs_booniehat2_marpatwd",
			"rhs_Booniehat_ocp",
			"rhs_Booniehat_ucp",
			"rhsusf_Bowman",
			"rhsusf_bowman_cap",
			"rhsusf_opscore_aor1",
			"rhsusf_opscore_aor1_pelt",
			"rhsusf_opscore_aor1_pelt_nsw",
			"rhsusf_opscore_aor2",
			"rhsusf_opscore_aor2_pelt",
			"rhsusf_opscore_aor2_pelt_nsw",
			"rhsusf_opscore_bk",
			"rhsusf_opscore_bk_pelt",
			"rhsusf_opscore_coy_cover",
			"rhsusf_opscore_coy_cover_pelt",
			"rhsusf_opscore_fg",
			"rhsusf_opscore_fg_pelt",
			"rhsusf_opscore_fg_pelt_cam",
			"rhsusf_opscore_fg_pelt_nsw",
			"rhsusf_opscore_mc_cover",
			"rhsusf_opscore_mc_cover_pelt",
			"rhsusf_opscore_mc_cover_pelt_nsw",
			"rhsusf_opscore_mc_cover_pelt_cam",
			"rhsusf_opscore_mc",
			"rhsusf_opscore_mc_pelt",
			"rhsusf_opscore_mc_pelt_nsw",
			"rhsusf_opscore_paint",
			"rhsusf_opscore_paint_pelt",
			"rhsusf_opscore_paint_pelt_nsw",
			"rhsusf_opscore_paint_pelt_nsw_cam",
			"rhsusf_opscore_rg_cover",
			"rhsusf_opscore_rg_cover_pelt",
			"rhsusf_opscore_ut",
			"rhsusf_opscore_ut_pelt",
			"rhsusf_opscore_ut_pelt_cam",
			"rhsusf_opscore_ut_pelt_nsw",
			"rhsusf_opscore_ut_pelt_nsw_cam",
			"rhsusf_hgu56p",
			"rhsusf_hgu56p_mask",
			"RHS_jetpilot_usaf",
			"rhsusf_lwh_helmet_M1942",
			"rhsusf_lwh_helmet_marpatd",
			"rhsusf_lwh_helmet_marpatd_ess",
			"rhsusf_lwh_helmet_marpatd_headset",
			"rhsusf_lwh_helmet_marpatwd",
			"rhsusf_lwh_helmet_marpatwd_blk_ess",
			"rhsusf_lwh_helmet_marpatwd_headset_blk",
			"rhsusf_lwh_helmet_marpatwd_headset",
			"rhsusf_lwh_helmet_marpatwd_ess",
			"rhsusf_mich_bare",
			"rhsusf_mich_bare_alt",
			"rhsusf_mich_bare_headset",
			"rhsusf_mich_bare_norotos",
			"rhsusf_mich_bare_norotos_alt",
			"rhsusf_mich_bare_norotos_alt_headset",
			"rhsusf_mich_bare_norotos_arc",
			"rhsusf_mich_bare_norotos_arc_alt",
			"rhsusf_mich_bare_norotos_arc_alt_headset",
			"rhsusf_mich_bare_norotos_arc_headset",
			"rhsusf_mich_bare_norotos_headset",
			"rhsusf_mich_bare_semi",
			"rhsusf_mich_bare_alt_semi",
			"rhsusf_mich_bare_semi_headset",
			"rhsusf_mich_bare_norotos_semi",
			"rhsusf_mich_bare_norotos_alt_semi",
			"rhsusf_mich_bare_norotos_alt_semi_headset",
			"rhsusf_mich_bare_norotos_arc_semi",
			"rhsusf_mich_bare_norotos_arc_alt_semi",
			"rhsusf_mich_bare_norotos_arc_alt_semi_headset",
			"rhsusf_mich_bare_norotos_arc_semi_headset",
			"rhsusf_mich_bare_norotos_semi_headset",
			"rhsusf_mich_bare_tan",
			"rhsusf_mich_bare_alt_tan",
			"rhsusf_mich_bare_tan_headset",
			"rhsusf_mich_bare_norotos_tan",
			"rhsusf_mich_bare_norotos_alt_tan",
			"rhsusf_mich_bare_norotos_alt_tan_headset",
			"rhsusf_mich_bare_norotos_arc_tan",
			"rhsusf_mich_bare_norotos_arc_alt_tan",
			"rhsusf_mich_bare_norotos_arc_alt_tan_headset",
			"rhsusf_mich_bare_norotos_tan_headset",
			"rhsusf_mich_helmet_marpatd",
			"rhsusf_mich_helmet_marpatd_alt",
			"rhsusf_mich_helmet_marpatd_alt_headset",
			"rhsusf_mich_helmet_marpatd_headset",
			"rhsusf_mich_helmet_marpatd_norotos",
			"rhsusf_mich_helmet_marpatd_norotos_arc",
			"rhsusf_mich_helmet_marpatd_norotos_arc_headset",
			"rhsusf_mich_helmet_marpatd_norotos_headset",
			"rhsusf_mich_helmet_marpatwd",
			"rhsusf_mich_helmet_marpatwd_alt",
			"rhsusf_mich_helmet_marpatwd_alt_headset",
			"rhsusf_mich_helmet_marpatwd_headset",
			"rhsusf_mich_helmet_marpatwd_norotos",
			"rhsusf_mich_helmet_marpatwd_norotos_arc",
			"rhsusf_mich_helmet_marpatwd_norotos_arc_headset",
			"rhsusf_mich_helmet_marpatwd_norotos_headset",
			"rhsusf_patrolcap_ocp",
			"rhsusf_patrolcap_ucp",
			"rhsusf_protech_helmet",
			"rhsusf_protech_helmet_ess",
			"rhsusf_protech_helmet_rhino",
			"rhsusf_protech_helmet_rhino_ess",
			"rhs_8point_marpatd",
			"rhs_8point_marpatwd",
			"tf47_beret",

			//GOOGLES
			"rhs_googles_yellow",
			"rhs_googles_orange",
			"rhs_googles_clear",
			"rhs_googles_black",
			"rhs_ess_black",
			"G_Bandanna_tan",
			"G_Bandanna_oli",
			"G_Bandanna_khk",
			"G_B_Diving",


			//NVGs
			"rhsusf_ANPVS_14",
			"rhsusf_ANPVS_15",
			"rhsusf_Rhino",

			//BINOCULARS
			"Rangefinder",
			"Binocular",
			"Laserdesignator",
			"lerca_1200_black",
			"lerca_1200_tan",
			"Leupold_Mk4",
			"ACE_Vector",
			"ACE_Yardage450",
			"ACE_MX2A",

			//MAP
			"ItemMap",

			//GPSs
			"ItemGPS",

			//COPASS
			"ItemCompass",

			//RADIOS
			"tf_anprc152",
			"tf_rf7800str",


			//WATCHES
			"ItemWatch",
			"tf_microdagr",
			"ACE_Altimeter",

			//ACE Stuff
			"ACE_VMH3",
			"ACE_VMM3",
			"ACE_HuntIR_M203",
			"ACE_M14",
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_HiOrange",
			"ACE_Chemlight_HiRed",
			"ACE_Chemlight_HiWhite",
			"ACE_Chemlight_HiYellow",
			"ACE_Chemlight_IR",
			"ACE_Chemlight_Orange",
			"ACE_Chemlight_White",
			"ACE_FlareTripMine_Mag",
			"ACE_M84",
			"ACE_HandFlare_White",
			"ACE_HandFlare_Red",
			"ACE_HandFlare_Green",
			"ACE_HandFlare_Yellow",
			"ACE_TacticalLadder_Pack",
			"ACE_NonSteerableParachute",
			"ACE_Yardage450",
			"ACE_MX2A",
			"ACE_Altimeter",
			"ACE_RangeCard",
			"ACE_Kestrel4500",
			"ACE_EarPlugs",
			"ACE_DefusalKit",
			"ACE_Clacker",
			"ACE_DAGR",
			"ACE_CableTie",
			"ACE_IR_Strobe_Item",
			"ACE_ATragMX",
			"ACE_Tripod",
			"ACE_SpottingScope",
			"ACE_Sandbag_empty",
			"ACE_SpareBarrel",
			"ACE_RangeTable_82mm",
			"ACE_microDAGR",
			"ACE_bodyBag",
			"ACE_surgicalKit",
			"ACE_personalAidKit",
			"ACE_quikclot",
			"ACE_salineIV_250",
			"ACE_salineIV_500",
			"ACE_salineIV",
			"ACE_bloodIV_250",
			"ACE_bloodIV_500",
			"ACE_bloodIV",
			"ACE_plasmaIV_250",
			"ACE_plasmaIV_500",
			"ACE_plasmaIV",
			"ACE_epinephrine",
			"ACE_Adenosine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_elasticBandage",
			"ACE_packingBandage",
			"ACE_fieldDressing",
			"ACE_MapTools",
			"ACE_wirecutter",
			"ACE_UAVBattery",
			"ACE_HuntIR_monitor",
			"ACE_Banana",
			"ACE_Flashlight_MX991",
			"ACE_Flashlight_KSF1",
			"ACE_Flashlight_XL50",
			"ACE_SpraypaintBlack",
			"ACE_SpraypaintBlue",
			"ACE_EntrenchingTool",
			"ACE_SpraypaintGreen",
			"ACE_SpraypaintRed",
			"ACE_Sandbag_empty",
			"ACE_RangeTable_M119",
			"ToolKit",
			"MineDetector",

			//ATACHMENTS Pistol

			//ATACHMENTS Rifle
			"rhs_weap_optic_smaw",

			"rhsusf_acc_nt4_black",
			"rhsusf_acc_nt4_tan",
			"rhsusf_acc_rotex5_grey",
			"rhsusf_acc_rotex5_tan",

			"rhsusf_acc_ACOG_USMC",
			"rhsusf_acc_ACOG2_USMC",
			"rhsusf_acc_ACOG3_USMC",
			"rhsusf_acc_ACOG_anpvs27",

			"rhsusf_acc_grip1",
			"rhsusf_acc_grip2",
			"rhsusf_acc_grip2_tan",
			"rhsusf_acc_grip3",
			"rhsusf_acc_grip3_tan",

			"rhsusf_acc_anpeq15",
			"rhsusf_acc_anpeq15_light",
			"rhsusf_acc_anpeq15_bk",
			"rhsusf_acc_anpeq15_bk_light",
			"rhsusf_acc_anpeq15side",
			"rhsusf_acc_anpeq15side_bk",
			"rhsusf_acc_anpeq15_top",
			"rhsusf_acc_anpeq15_bk_top",
			"rhsusf_acc_anpeq15_wmx",
			"rhsusf_acc_anpeq15_wmx_light",
			"rhsusf_acc_M952V",
			"rhsusf_acc_wmx",
			"rhsusf_acc_anpeq15A",
			"rhsusf_acc_SFMB556",
			"rhsusf_acc_SF3P556",
			"rhsusf_acc_harris_bipod",
			"rhsusf_acc_SR25S",
			"rhsusf_acc_compm4",
			"rhsusf_acc_anpvs27",
			"rhsusf_acc_LEUPOLDMK4",
			"rhsusf_acc_LEUPOLDMK4_2",
			"rhsusf_acc_ELCAN",
			"rhsusf_acc_ELCAN_ard",
			"rhsusf_acc_eotech_552",
			"rhsusf_acc_ACOG",
			"rhsusf_acc_ACOG2",
			"rhsusf_acc_ACOG3",
			"rhsusf_acc_M2A1",
			"rhsusf_acc_M2010S",
			"rhsusf_acc_premier_low",
			"rhsusf_acc_premier_anpvs27",
			"rhsusf_acc_premier",
			"rhsusf_acc_SpecterDR",
			"rhsusf_acc_SpecterDR_OD",
			"rhsusf_acc_SpecterDR_D",
			"rhsusf_acc_SpecterDR_A",
			"rhsusf_acc_EOTECH",
			"rhsusf_acc_eotech_xps3",

			//ATTACHMENTS
			"tf47_optic_m3maaws",
			"tf47_optic_smaw"




		], false, true] call xla_fnc_addVirtualItemCargo;
		// TFAR UNIQUE TO GENERIC
		_forceReplace = [];
		_forceReplace resize 1998;
		for [{_i=0}, {_i<999}, {_i=_i+1}] do {
				_forceReplace set [_i, ["tf_anprc152_" + (str (_i+1)), "tf_anprc152"]];
				_forceReplace set [_i+999, ["tf_rf7800str_" + (str (_i+1)), "tf_rf7800str"]];
		};
		//[_X, [WEST_SIDE,FRIENDLY_SIDE],true,false] call XLA_fnc_addVirtualSideCargo;
		//[_X, ["arifle_Katiba_BASE_F"],true,false] call XLA_fnc_addVirtualWeaponCargo;

		// Start the arsenal on it
		_addActionText = "<t color=""#11F22F"">" + "Arsenal";
		["AmmoboxInit",[_X,false,{true},_addActionText,false,_forceReplace]] spawn XLA_fnc_arsenal;

} forEach [arsenal1, arsenal2, arsenal3, arsenal4, arsenal5, arsenal6];
